[package]
name = "c8_device"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
c8_audio = { workspace = true }

[lints]
workspace = true

[lib]
test = true
doctest = true
