[package]
name = "c8_audio"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[lints]
workspace = true
