[package]
name = "c8_audio"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = { workspace = true }

#wasm-bindgen = { version = "0.2" }
#wasm-bindgen-futures = "0.4"
#web-sys = { version = "0.3", features = [
#    "MouseEvent",
#    "Window",
#    "Document",
#    "Element",
#    "HtmlElement",
#    "console",
#] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "MouseEvent",
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "console",
] }

[lints]
workspace = true
